### ISSUE TITLE
"longjmp causes uninitialized stack frame" on rapid scrolling through a PDF

### ISSUE THREAD

**Issue by Dook97** [pwmt/zathura-pdf-mupdf#70] opened 2024-06-04 16:16 UTC
```
zathura 0.5.6
girara 0.4.4 (runtime: 0.4.4)
(plugin) pdf-mupdf (0.4.2) (/usr/lib/zathura/libpdf-mupdf.so)
```

The `zathura-pdf-mupdf` plugin was used to view a pdf file with not entirely trivial contents (a `.pptx` converted by libreoffice). Then I simply held `shift+j`. I can reproduce the crash without much effort, though it doesn't always happen.

Below the output of `coredumpctl` as well as the core file itself.

```           PID: 42024 (zathura)
           UID: 1000 (j3)
           GID: 1000 (j3)
        Signal: 6 (ABRT)
     Timestamp: Tue 2024-06-04 17:45:21 CEST (2min 26s ago)
  Command Line: zathura NPRG051-F1-language.pdf
    Executable: /usr/bin/zathura
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (j3)
       Boot ID: c31587105cb7460fb8a0faed1ea2be8a
    Machine ID: 2d1fc6389da040268de649a48209e0d1
      Hostname: tp
       Storage: /var/lib/systemd/coredump/core.zathura.1000.c31587105cb7460fb8a0faed1ea2be8a.42024.1717515921000000.zst (present)
  Size on Disk: 33.1M
       Message: Process 42024 (zathura) of user 1000 dumped core.
                Stack trace of thread 42030:
                #0  0x00007df5a4c8ce44 n/a (libc.so.6 + 0x94e44)
                pwmt/zathura#1  0x00007df5a4c34a30 raise (libc.so.6 + 0x3ca30)
                pwmt/zathura#2  0x00007df5a4c1c4c3 abort (libc.so.6 + 0x244c3)
                pwmt/zathura#3  0x00007df5a4c1d354 n/a (libc.so.6 + 0x25354)
                pwmt/zathura#4  0x00007df5a4d1a259 __fortify_fail (libc.so.6 + 0x122259)
                pwmt/zathura#5  0x00007df5a4d19211 n/a (libc.so.6 + 0x121211)
                pwmt/zathura#6  0x00007df5a4d1a933 __longjmp_chk (libc.so.6 + 0x122933)
                pwmt/zathura#7  0x00007df5910a549d n/a (libmupdf.so.24.2 + 0xa549d)
                pwmt/zathura#8  0x00007df5910a5503 fz_rethrow (libmupdf.so.24.2 + 0xa5503)
                pwmt/zathura#9  0x00007df591168d55 n/a (libmupdf.so.24.2 + 0x168d55)
                pwmt/zathura#10 0x00007df591168ed9 pdf_process_raw_contents (libmupdf.so.24.2 + 0x168ed9)
                pwmt/zathura#11 0x00007df5911690ac pdf_process_contents (libmupdf.so.24.2 + 0x1690ac)
                pwmt/zathura#12 0x00007df59119a669 n/a (libmupdf.so.24.2 + 0x19a669)
                pwmt/zathura#13 0x00007df59119aa81 pdf_run_page_contents_with_usage (libmupdf.so.24.2 + 0x19aa81)
                pwmt/zathura#14 0x00007df59106e66c fz_run_page_contents (libmupdf.so.24.2 + 0x6e66c)
                pwmt/zathura#15 0x00007df59106e877 fz_run_page (libmupdf.so.24.2 + 0x6e877)
                pwmt/zathura#16 0x00007df5a3854990 n/a (libpdf-mupdf.so + 0x4990)
                pwmt/zathura#17 0x00006208b81829b1 n/a (zathura + 0x189b1)
                pwmt/zathura#18 0x00007df5a50441f3 n/a (libglib-2.0.so.0 + 0x921f3)
                pwmt/zathura#19 0x00007df5a503e236 n/a (libglib-2.0.so.0 + 0x8c236)
                pwmt/zathura#20 0x00007df5a4c8aded n/a (libc.so.6 + 0x92ded)
                pwmt/zathura#21 0x00007df5a4d0e0dc n/a (libc.so.6 + 0x1160dc)
                Stack trace of thread 42026:
                #0  0x00007df5a4d0039d __poll (libc.so.6 + 0x10839d)
                pwmt/zathura#1  0x00007df5a50708fd n/a (libglib-2.0.so.0 + 0xbe8fd)
                pwmt/zathura#2  0x00007df5a500df95 g_main_context_iteration (libglib-2.0.so.0 + 0x5bf95)
                pwmt/zathura#3  0x00007df5a500dfea n/a (libglib-2.0.so.0 + 0x5bfea)
                pwmt/zathura#4  0x00007df5a503e236 n/a (libglib-2.0.so.0 + 0x8c236)
                pwmt/zathura#5  0x00007df5a4c8aded n/a (libc.so.6 + 0x92ded)
                pwmt/zathura#6  0x00007df5a4d0e0dc n/a (libc.so.6 + 0x1160dc)
                Stack trace of thread 42027:
                #0  0x00007df5a4d0be9d syscall (libc.so.6 + 0x113e9d)
                pwmt/zathura#1  0x00007df5a50699e0 g_cond_wait (libglib-2.0.so.0 + 0xb79e0)
                pwmt/zathura#2  0x00007df5a4fd78dc n/a (libglib-2.0.so.0 + 0x258dc)
                pwmt/zathura#3  0x00007df5a5043687 n/a (libglib-2.0.so.0 + 0x91687)
                pwmt/zathura#4  0x00007df5a503e236 n/a (libglib-2.0.so.0 + 0x8c236)
                pwmt/zathura#5  0x00007df5a4c8aded n/a (libc.so.6 + 0x92ded)
                pwmt/zathura#6  0x00007df5a4d0e0dc n/a (libc.so.6 + 0x1160dc)
                Stack trace of thread 42029:
                #0  0x00007df5a4d0039d __poll (libc.so.6 + 0x10839d)
                pwmt/zathura#1  0x00007df5a50708fd n/a (libglib-2.0.so.0 + 0xbe8fd)
                pwmt/zathura#2  0x00007df5a500f787 g_main_loop_run (libglib-2.0.so.0 + 0x5d787)
                pwmt/zathura#3  0x00007df5a52124b4 n/a (libgio-2.0.so.0 + 0x1124b4)
                pwmt/zathura#4  0x00007df5a503e236 n/a (libglib-2.0.so.0 + 0x8c236)
                pwmt/zathura#5  0x00007df5a4c8aded n/a (libc.so.6 + 0x92ded)
                pwmt/zathura#6  0x00007df5a4d0e0dc n/a (libc.so.6 + 0x1160dc)
                Stack trace of thread 42024:
                #0  0x00007df5a4d0039d __poll (libc.so.6 + 0x10839d)
                pwmt/zathura#1  0x00007df5a50708fd n/a (libglib-2.0.so.0 + 0xbe8fd)
                pwmt/zathura#2  0x00007df5a500f787 g_main_loop_run (libglib-2.0.so.0 + 0x5d787)
                pwmt/zathura#3  0x00007df5a55e390f gtk_main (libgtk-3.so.0 + 0x1e390f)
                pwmt/zathura#4  0x00006208b8176f53 main (zathura + 0xcf53)
                pwmt/zathura#5  0x00007df5a4c1dc88 n/a (libc.so.6 + 0x25c88)
                pwmt/zathura#6  0x00007df5a4c1dd4c __libc_start_main (libc.so.6 + 0x25d4c)
                pwmt/zathura#7  0x00006208b81775b5 _start (zathura + 0xd5b5)
                Stack trace of thread 42028:
                #0  0x00007df5a4d0be9d syscall (libc.so.6 + 0x113e9d)
                pwmt/zathura#1  0x00007df5a506a337 g_cond_wait_until (libglib-2.0.so.0 + 0xb8337)
                pwmt/zathura#2  0x00007df5a4fd78a5 n/a (libglib-2.0.so.0 + 0x258a5)
                pwmt/zathura#3  0x00007df5a4fd7a18 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x25a18)
                pwmt/zathura#4  0x00007df5a5044080 n/a (libglib-2.0.so.0 + 0x92080)
                pwmt/zathura#5  0x00007df5a503e236 n/a (libglib-2.0.so.0 + 0x8c236)
                pwmt/zathura#6  0x00007df5a4c8aded n/a (libc.so.6 + 0x92ded)
                pwmt/zathura#7  0x00007df5a4d0e0dc n/a (libc.so.6 + 0x1160dc)
                Stack trace of thread 42025:
                #0  0x00007df5a4d0be9d syscall (libc.so.6 + 0x113e9d)
                pwmt/zathura#1  0x00007df5a50699e0 g_cond_wait (libglib-2.0.so.0 + 0xb79e0)
                pwmt/zathura#2  0x00007df5a4fd78dc n/a (libglib-2.0.so.0 + 0x258dc)
                pwmt/zathura#3  0x00007df5a4fd794d g_async_queue_pop (libglib-2.0.so.0 + 0x2594d)
                pwmt/zathura#4  0x00007df5a4acec48 n/a (libpangoft2-1.0.so.0 + 0x9c48)
                pwmt/zathura#5  0x00007df5a503e236 n/a (libglib-2.0.so.0 + 0x8c236)
                pwmt/zathura#6  0x00007df5a4c8aded n/a (libc.so.6 + 0x92ded)
                pwmt/zathura#7  0x00007df5a4d0e0dc n/a (libc.so.6 + 0x1160dc)
                ELF object binary architecture: AMD x86-64
More than one entry matches, ignoring rest.
```

**Comment by sebastinas** [comment] 2024-06-04 16:57
Duplicate of #68.

**Closed by sebastinas** 2024-06-04 16:57 UTC
Labels: bug, duplicate
